[Writable]
LogLevel = 'INFO'

    [Writable.StoreAndForward]
    Enabled = false
    RetryInterval = 50000 # 5mins
    MaxRetryCount = 10

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is a sample Application Service which use of TargetType'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = './logs/simple-filter-xml.log'

[Clients]
  [Clients.Logging]
  Protocol = "http"
  Host = "localhost"
  Port = 48061
  [Clients.Command]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48082

# This example expect custom type via HTTP Trigger
[Binding]
Type="http"

[ApplicationSettings]
DeviceID = "7cccb1a0-8e26-4feb-95c7-423e49559017"
CommandID = "6663264d-c62e-49c6-bec3-96964570a4f9"
